from typing import Any
import enum


class ResultCode(enum.Enum):
    LOGIN_FAILED = 0
    LOGIN_SUCCESS = 1
    MEAL_SAVED_SUCCESS = 2
    MEAL_SAVED_FAILED = 3
    MEAL_UPDATED_SUCCESS = 4
    MEALED_UPDATED_FAILED = 5
    MEALED_DELETED_SUCCESS = 6
    MEAL_DELETED_FAILED = 7
    MEALS_RETRIEVED_SUCCESS = 8
    MEALS_RETRIEVED_FAILED = 9
